app:
  jwt-expiration-milliseconds: 604800000
  jwt-secret: 'OTRAROD654222'
spring:
  datasource:
    url: jdbc:mysql://p07-eu131.activaserver.com:3306/otra_ronda_
    password: q*D6gb42
    username: adminroot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
        
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/master-change-log.xml
    default-schema: otra_ronda_local
  logging:
    level:
      liquibase: INFO