app:
  jwt-expiration-milliseconds: 604800000
  jwt-secret: 'COQUITOS589877445'
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/desa_daviddev
    password: 19616798
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  servlet:
      tomcat:
          max-swallow-size: -1
          max-http-form-post-size: -1B
  flaway:
     locations: classpath:/db/migration,classpath:/db/testdata